### ISSUE TITLE
Plugin forces to install 'oc' client manually

### ISSUE THREAD

**Issue by nennete** [openshift/jenkins-client-plugin#11]
Hi,

I have got Jenkins outside Openshift. I have to install the 'oc' client manually if I want to use this plugin. It would be great if the plugin comes with the 'oc' client to be installed in the Jenkins machine.

Thanks

**Comment by gabemontero** [comment]
@nennete - just to confirm, by installing manually, you mean navigate to Manage Jenkins -> Global Tool Configuration -> and find the "OpenShift Client Tools" section, correct?

**Comment by gabemontero** [comment]
Pending confirmation on my question to @nennete , enhancing the "jenkins outside of openshift" scenario so that the `oc` binary is automatically pulled in, the only possible solutions that come to my mind are:

1) have the plugin automatically generate "Global Tool Configuration -> OpenShift Client Tools" config on startup such that the oc binary will be placed in the existing path of the Jenkins server ... seems problematic to me on several fronts, where you have to either make assumptions on the path, or you have to make the location configurable (which breaks the "doing it automatically" premise), or you have to update the path in your pipeline script as already discussed in the readme.  Of course which version of `oc` to pull in has similar concerns.  Also, the config format for the global tool config is not public or standardized per se

2) have the plugin package the `oc` binary in its hpi file, and then again have to copy it to somewhere on the path, manage the path, etc.

Seems like a non-starter or low priority (where perhaps is better to wait and see if upstream jenkins further enhances how to introduce binary tools, or expands the global library support somehow to facilitate this).

@bparees @jupierce - thoughts ?

**Comment by bparees** [comment]
> @bparees @jupierce - thoughts ?

agree w/ what you said.  we definitely don't want to package the oc binary inside the plugin.

**Comment by nennete** [comment]
@gabemontero - What I did, it was to install the plugin directly through Jenkins (here in repo you recommend to build the project locally and install it manually, instead). 

My Jenkins lives in different machine than Openshift.

Then, the Jenkins job which leverages Openshift commands threw an exception saying something like: `oc command not found`. Sorry, I had to revert the plugin so I cannot post any screenshot.

Therefore, I reckon it is useful to, somehow, let the plugin also install the `oc` client in case there is no installation already.

**Comment by gabemontero** [comment]
OK, thanks for the update @nennete - so I'm taking from you response that you did *NOT* employ the "Global Tool Configuration -> OpenShift Client Tools" configuration path ... i.e. the instructions at https://github.com/openshift/jenkins-client-plugin#setting-up-jenkins-nodes

Setting up the binary in that fashion, or using the openshift jenkins image, is certainly a prereq, as noted at the top of the repo's readme at https://github.com/openshift/jenkins-client-plugin#overview

As I mentioned above, I don't see us "automatically" installing the `oc` binary in the "jenkins outside of the openshift jenkins image" scenario at this time.

You are correct that https://github.com/openshift/jenkins-client-plugin#installing is out of date.  The plugin is available at the jenkins update center.  I'll update the README momentarily.

**Comment by gabemontero** [comment]
readme at https://github.com/openshift/jenkins-client-plugin updated re: how to install

the analogous readme at https://github.com/jenkinsci/openshift-client-plugin will get updated the next time we cut a new release.

**Comment by gabemontero** [comment]
We've finished our review, and will not be moving forward at this time with having the client plugin *automatically* install the `oc` binary when running outside of the openshift image.  There is no easy, clean, safe way to do it, and using Jenkins' "Global Tool configuration" to manually install binaries like this is the preferred option from a general Jenkins perspective.

Thanks for the interest.
