### ISSUE TITLE
Escaping parameters with spaces

### ISSUE THREAD

**Issue by gomesp** [openshift/jenkins-client-plugin#177]
Hi team

I am not sure if this is a bug or a call for help. 

In one of my projects I am trying to create a deployment config from a template file with parameters. To do that I run (roughly):
```
String[] templateParams = ["-p","AD_GROUP=${adGroup}"]                                                     
def template = "${TEMPLATE_PATH}/dc-webservices.yml",
openshift.process(template, templateParams)
```
The template YAML has a default value with spaces and that works:

```
  - name: AD_GROUP
    required: true
    value: Application Production Logs
```

However if I override the parameter in the Jenkinsfile (in the first snippet) with a value with spaces, I get the following error:

```
ERROR: process returned an error;
{reference={}, err=error: template "Users" could not be found, verb=process, cmd=oc --server=https://xxxxx:8443 --namespace=xxxx --token=XXXXX process -f /tmp/process1812368489278526389.markup -p AD_GROUP="All Users" -o=json , out=, status=1}
```

I have tried setting ```${value}``` to:

```
adGroup = '"All Users"' # (single quote, then double quote)
adGroup = "'All Users'" # (double quote, then single quote)
adGroup = '\"All Users\"' # (escaping double quotes)
```
Have I encountered a bug, or am I not escaping the variable correctly? I appreciate any help that could be given here.
Thanks

**Comment by gomesp** [comment]
BTW, running the same command from the shell works.

**Comment by coreydaley** [comment]
@gomesp Can you try setting openshift.verbose in your Jenkinsfile and then run it with the default value for AD_GROUP and look at how it gets quoted?

**Comment by TomSchmitz** [comment]
Ich bin bis 17.09.2018 abwesend.
I am out of the office until 17.09.2018.

Ich werde Ihre Nachricht nach meiner Rückkehr beantworten.

In dringenden Fällen wenden Sie sich bitte an Frank Becker (AC-6606)


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[openshift/jenkins-client-plugin] Escaping parameters with spaces (#177)"
gesendet am 07.09.2018 12:59:05.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.

**Comment by gomesp** [comment]
@coreydaley Thanks for your response. The error below was from Jenkins running with Openshift in verbose mode.

For ```adGroup = '"All Users"' # (single quote, then double quote):```
```
ERROR: process returned an error;
{reference={}, err=error: template "Users" could not be found, verb=process, cmd=oc --server=https://xxxxx:8443 --namespace=xxxx --token=XXXXX process -f /tmp/process1812368489278526389.markup -p AD_GROUP="All Users" -o=json , out=, status=1}
```

For "'All Users'" # (double quote, then single quote)
```
ERROR: process returned an error;
{reference={}, err=error: template "Users" could not be found, verb=process, cmd=oc --server=https://xxxxx:8443 --namespace=xxxx --token=XXXXX process -f /tmp/process1812368489278526389.markup -p AD_GROUP='All Users' -o=json , out=, status=1}
```

For adGroup = "All\\ Users"
```
ERROR: process returned an error;
{reference={}, err=error: template "Users" could not be found, verb=process, cmd=oc --server=https://xxxxx:8443 --namespace=xxxx --token=XXXXX process -f /tmp/process1812368489278526389.markup -p AD_GROUP=All\ Users -o=json , out=, status=1}
```

**Comment by TomSchmitz** [comment]
Ich bin bis 17.09.2018 abwesend.
I am out of the office until 17.09.2018.

Ich werde Ihre Nachricht nach meiner Rückkehr beantworten.

In dringenden Fällen wenden Sie sich bitte an Frank Becker (AC-6606)


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[openshift/jenkins-client-plugin] Escaping parameters with spaces (#177)"
gesendet am 10.09.2018 00:16:04.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.

**Comment by coreydaley** [comment]
@gomesp I meant to run it with the default value in the yaml file with openshift.verbose set

 - name: AD_GROUP
    required: true
    value: Application Production Logs

to see how that gets quoted when it actually runs the command.

**Comment by gabemontero** [comment]
hey @gomesp @coreydaley  - some reports or repro attemps, and possible work arounds

1) First, when referencing a template I previously created in my namespace (postgresql-ephemeral), I see the following command process the template parameter correctly

`openshift.process('postgresql-ephemeral', '-p', 'POSTGRESQL_PASSWORD="All Users"')`

where I of course replaced `AD_GROUP` with an actual parameter in my template

2) Next, looking at the current code at https://github.com/openshift/jenkins-client-plugin/blob/master/src/main/resources/com/openshift/jenkins/plugins/OpenShiftDSL.groovy#L720-L757 as well as taking an look  back historically, the `openshift.process` method has never taken a relative file location as the template parameter as indicated in the description.

As expressed in the help, the valid input types are 
1) the template object expressed as a java/groovy Map
2) the template object expressed as json/yaml stored in a string
3) a http ref to a file container json/yaml

So yes, it is not as fully functioned as the `oc` binary from the command line right now.

Don't see how any form as listed in the description could work.

I would expect a user to read in the contents of their yaml file into a variable using the jenkins pipeline DSL for reading in files, and then pass the contents to `openshift.process`.  

Are you in fact doing that @gomesp, and that is what you meant by using 'roughly' in your description?

I think that is the case, given I see use of markup files in your comment https://github.com/openshift/jenkins-client-plugin/issues/177#issuecomment-419748983 output, but wanted to make sure.

3) If so, that can get tricky with the plugin in its current form, since the template may have quotes as well.

I would suggest first running `openshift.create` on the file to create the template, and then run `openshift.process` in the same fashion I did in 1)

If this is the crux of the issue, then yes, this plugin is not as fully functional as `oc` from the command line wrt to parameter processing (in a lot of ways, groovy in jenkins gets in our way).  We *might* be able to look at a feature add, but most likely, this would be a restriction.

But let's confirm the details, and go from there.

**Comment by gomesp** [comment]
Hi @gabemontero thanks for the feedback. I'm going to create a full example that I can put on Github and share with you in the next day or two.

**Comment by TomSchmitz** [comment]
Ich bin bis 17.09.2018 abwesend.
I am out of the office until 17.09.2018.

Ich werde Ihre Nachricht nach meiner Rückkehr beantworten.

In dringenden Fällen wenden Sie sich bitte an Frank Becker (AC-6606)


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[openshift/jenkins-client-plugin] Escaping parameters with spaces (#177)"
gesendet am 16.09.2018 12:13:40.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.

**Comment by gomesp** [comment]
Hi @gabemontero I can reproduce my bug using this: https://gist.github.com/gomesp/079a9cdca60a4867076b910b878a9af0

**Comment by gabemontero** [comment]
Hey @gomesp - so those 2 files were very instructive, though I'll need some follow ups:

1) we have not done any testing with content returned from the `libraryResource` step with shared libraries  .... most likely the string returned does not meet the json/yaml format requirement I noted in https://github.com/openshift/jenkins-client-plugin/issues/177#issuecomment-420049392

2) that said, I don't have any sample shared libraries available to try to add this and reproduce ... and it might be a bit before I could construct one

3) would it be possible for you to reproduce where you print the `template` variable from `def template = libraryResource "templates/smoketest/dc.yml"` in you sample pipeline?

I would hope I could make a conclusive statement after that.

**Comment by gomesp** [comment]
Thanks @gabemontero I will create a full github project to help you sorting this out then. 

The file lives under in a [shared pipeline](https://jenkins.io/doc/book/pipeline/shared-libraries/) under the ```resources``` folder. This groovy file is just a global library that the Jenkinsfile can refer to.

When I produce the full example I will include the debug logs with the value from the ```template``` variable as you requested.

Thanks!

**Comment by gabemontero** [comment]
On Tue, Sep 18, 2018 at 7:11 PM, Pablo <notifications@github.com> wrote:

> Thanks @gabemontero <https://github.com/gabemontero> I will create a full
> github project to help you sorting this out then.
>
> The file lives under in a shared pipeline
> <https://jenkins.io/doc/book/pipeline/shared-libraries/> under the
> resources folder. This groovy file is just a global library that the
> Jenkinsfile can refer to.
>
Yep, understood that.  Just don't have the bandwidth to build a shared lib
for testing right now.

> When I produce the full example I will include the debug logs with the
> value from the template variable as you requested.
>
Perfect - thanks!

I might be able to construct a test in parallel with what you provided, but
alter how we suck in the template, for comparisons.  i.e.
1) create the template outside the pipeline, but then reference it
2) maybe rsync the template to my pod, and use `readFile`

If I can, I'll report here.

**Comment by gabemontero** [comment]
OK I believe I have now reproduced this locally.  

The key for me was literally passing in a parameter with a space vs. setting the variable to the value with a space, and then referencing it via `${varname}`

Most likely this is related to https://github.com/openshift/jenkins-client-plugin/issues/180 and what has been discovered there with env's not getting propagated.

I'll see about updating the new launcher code (vs. the old BourneShellScript code) to propagate the environment.

If the path for that proves untenable in the relatively short term, we may need to revert that change from BourneShellScript, but I'm somewhat optimisitc.

@bparees @vfreex FYI ^^

**Comment by gabemontero** [comment]
Ok I have a fix working for me locally for my reproducer.  Still testing, might tweak the impl, but should probably have  PR up my time Tuesday Sept 25.

**Comment by vfreex** [comment]
@gabemontero As discussed in https://github.com/openshift/jenkins-client-plugin/pull/176, a parameter with spaces is treated as multiple parameters unless being quoted for compatibility reasons. Personally I really don't like the idea of handling spaces or environment variables for the arguments passed into the DSL methods. Ideally it should pass all the parameters to the `oc` command as-is without any further processing. Environment variables can be expanded before calling the DSL method, like:

```groovy
withEnv("SOME_POD=foobar") {
  openshift.selector('pod', "${env.SOMEPOD}").object()
}
```

**Comment by gabemontero** [comment]
@vfreex @gomesp we definitely need to tolerate params with spaces for template processing (i.e. `openshift.process(...)`

Initial reaction I'm not enthralled with special case processing per verb.  But I need to revisit the various scenarios once more before I take a definitive stand.  This is on my to-do list for today.

**Comment by gabemontero** [comment]
I have a PR up that fixes my reproducer

**Comment by vfreex** [comment]
@gomesp Regarding to your example, parameters contains spaces should be quoted, like
`def templateParams = ["-p", "ACCESS_LOG_AD_GROUP='${adGroup}'"]` or `def templateParams = ["-p", "'ACCESS_LOG_AD_GROUP=${adGroup}'"]`

**Comment by gomesp** [comment]
@vfreex Thanks for the feedback. The issue I faced here was that even by trying all different ways to quote the parameters I could not provide the parameter value containing spaces to the template.

For what I saw in @gabemontero's PR this would fix it: https://github.com/openshift/jenkins-client-plugin/pull/182/commits/f2d265edc86bb096a770020f6c086f55e21e5944#diff-dcd07aa221d2ea9075cd77e4c245364aR68

**Comment by gabemontero** [comment]
@vfreex @gomesp yeah the need to say `"ACCESS_LOG_AD_GROUP='${adGroup}'"` instead of `"ACCESS_LOG_AD_GROUP=${adGroup}"` is too unnatural to me as a programmer, and even if we document its need, there will be too many folks who will miss that doc and open issues like this asking what is going on.

Hopefully I'll sort out handling this vs. our rsh/exec tests in a way that does not overly sadden us :-) and should have the change in today.

**Comment by gabemontero** [comment]
v1.0.18 of the plugin has been initiated with the jenkins update center
