### ISSUE TITLE
when doing openshift.withCluster how do you pass a custom CA?

### ISSUE THREAD

**Issue by itewk** [openshift/jenkins-client-plugin#205]
I want to use openshift.withCluster to log into a separate remote OCP cluster but I can't figure out how to specify a different trusted CA path to use rather then the default one that has the CA for the local cluster.

**Comment by gabemontero** [comment]
For injecting the cert into the trust store for jenkins, if that is what you mean, you got to follow their directions .... like https://support.cloudbees.com/hc/en-us/articles/203821254-How-to-install-a-new-SSL-certificate-

Most users have done this either by extending our openshift jenkins image, or modifying the deployment in order to 
- mount the cert (where the cert is defined in a secret or config map)
- either run as part of building the new image, or modifying the start of the container, to create the appropriate directories and call that `update-ca-trust` command the cloudbees post mentions ... if you are modifying the deployment command, after you do that , you need to call the image's existing entrypoint, etc.

Once you've got the cert injected, you follow the instructions at https://github.com/openshift/jenkins-client-plugin#configuring-an-openshift-cluster

**Comment by itewk** [comment]
@gabemontero we were hoping to avoid using the cluster configuraiton in the Jenkins UI and have all the configuration built into the pipeline itself, so using the `openshift.withCluster(URL, TOKEN)` syntax. I was hoping there was some way to do like `openshift.withCluster(URL, TOKEN, ANY_OTHER_PARAM_YOU_COULD_OTHERWISE_SET_IN_UI_SUCH_AS_CA)` for the short term I figured out the trick of setting `insecure://` to make it skip the CA validation.

**Comment by gabemontero** [comment]
yeah taking on CA configuration in Jenkins is not something that has been added to this plugin

certainly feel free to open an RFE
