### ISSUE TITLE
openshift.create() output format is always 'name'

### ISSUE THREAD

**Issue by ThomVivet** [openshift/jenkins-client-plugin#262]
I try to convert the following openshift shell command to openshift plugin syntax:
```
sh "oc create configmap frontend-config --namespace=${project} --from-file=config.js --dry-run -o json | oc apply -f-"
```

It should be:
```
openshift.apply(openshift.create("configmap", "frontend-config", "--dry-run", "--from-file=config.js").object())
```

But the configMap remains empty...

In fact the openshift.create() output format is always 'name' despite requested yaml:
```
cm = openshift.create("configmap", "frontend-config", "--dry-run", "--from-file=config.js", "--output=yaml")
echo "[INFO] ${cm.actions[0].cmd}"
//[INFO] oc ... create configmap frontend-config --dry-run --from-file=config.js --output=yaml -o=name 
```
You can see --output=yaml -o=name ...

So the appropriate command becomes:
```
apply = openshift.apply(openshift.raw("create configmap frontend-config --dry-run --from-file=config.js --output=yaml").actions[0].out)
```
... which is not friendly.
I expect the requested output format to be taken in account.

Context:
OpenShift Client Jenkins Plugin 1.0.29
And:
```
oc version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://10.xxx
openshift v3.11.98
kubernetes v1.11.0+d4cacc0
```

**Comment by TomSchmitz** [comment]
Ich bin bis 06.05.2019 abwesend.
I am out of the office until 06.05.2019.

Ich werde Ihre Nachricht nach meiner Rückkehr beantworten.

In dringenden Fällen wenden Sie sich bitte an Frank Becker (AC-6606)


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht
"[openshift/jenkins-client-plugin] openshift.create() output format is
always 'name' (#262)" gesendet am 03.05.2019 17:32:48.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.

**Comment by gabemontero** [comment]
Hi @ThomVivet 

Yep use of `-o=name` in its core `oc` invocations is a fundamental implementation detail of this plugin.  That is not going to change at this point.

Also, in general, the plugin tried to abstract out the major `oc` params in a more first class fashion.  Output of json or yaml was one of those.  Trying the special case those options down at the lower levels is messier.

So instead of trying to pass in `-o=yaml` as an arg into `openshift.create` or `openshift.raw`, you should us the `asYaml()` method on the `OpenShiftResourceSelector`

i.e. `openshift.apply(openshift.create(....).asYaml())`

Try that and let us know.

I could see updating the README's examples to include such a nested, pipe the output of one command as the input of another command, scenario.

@waveywaves @sthaha fyi ^^

**Comment by ThomVivet** [comment]
Thank you for your answer @gabemontero.
I just tried your idea using `.asYaml()`:
```openshift.apply(openshift.create("configmap", "frontend-config", "--dry-run", "--from-file=config.js").asYaml())```

... I have no error but the configMap remains _empty_ (I created it just before).

Under the hood it launched the following commands:
1. `oc create configmap frontend-config --dry-run --from-file=config.js -o=name`
2. `oc get configmap/frontend-config -o=yaml`
3. `oc apply -f workspace/apply3976741294167575270.markup -o=name`

According to this, how does the applied markup file (in \#3) could contain the file resulting from `oc create --dry-run` (in \#1) ...
Did I missed something ?

**Comment by gabemontero** [comment]
@ThomVivet no I missed the `--dry-run` from your earlier example.

Since you are not actually creating the configmap, the subsequent `oc get` the `asYaml()` call does will not find anything to dump the yaml for.

So yeah, since `oc create` does not have an `--ignore-if-already-exists`, your use of `openshift.raw(...)` is this plugin's only current solution to your scenario.

We should clarify in the documentation the situation around trying to force the output type and this plugin's design around `-o=name` in the short term, and this can get registered and a feature request in the long term.

**Comment by ThomVivet** [comment]
OK, thanks in advance for documentation update and the future feature

**Comment by gabemontero** [comment]
docs PR finally constructed ^^

**Comment by akram** [comment]
@gabemontero or @ThomVivet can you close the issue if the fix has been provided?

**Comment by ThomVivet** [comment]
Doc updated: https://github.com/openshift/jenkins-client-plugin/blob/master/README.md#aside-from-some-lessons-learned-by-our-users
