### ISSUE TITLE
Retrieve objects from several namespaces as a selector

### ISSUE THREAD

**Issue by racodond** [openshift/jenkins-client-plugin#276]
Hi,

If there's a way to retrieve objects from several namespaces as a selector? To achieve something similar to `oc get quota --all-namespaces` for instance?

Thank you

Regards,

David RACODON

**Comment by gabemontero** [comment]
Not currently @racodond 

It would require feature level work.

@waveywaves @akram FYI

**Comment by gabemontero** [comment]
yep in hindsight @waveywaves there is a cross namespace correlation

**Comment by racodond** [comment]
Thanks for your feedback guys!

**Comment by akram** [comment]
This is quite complex to implement, also because the `oc` does not allow to pass multiple to pass multiple namespaces.
The "workaround" for this is to add a loop in with you changed the withProject() closure and then have a call to `.selector()`.

We will close it in favour of the provided workaround.

/close
