### ISSUE TITLE
Error running commands outside withProject block

### ISSUE THREAD

**Issue by GolanTrevize10** [openshift/jenkins-client-plugin#36]
Hi, I am using the plugin version 0.9.5 with OC client 1.5.1 in a Jenkins server outside Openshift. When I try to run some commands like openshift.newProject or openshift.process outside a withProject block I get this error:

java.io.FileNotFoundException: /var/run/secrets/kubernetes.io/serviceaccount/namespace (No such file or directory)

If I put them inside a withProject block then they work.

**Comment by gabemontero** [comment]
The REST invocation for `oc process` involve the target project/namespace in the URI, so `openshift.process` will be no different.

So that *has* to run within a `withProject` block.

That is *NOT* the case with `oc new-project` and by extension `openshift.newProject`.  I'll use this issue to make the change to not retrieve the project/namespace when executing that command.

**Comment by gabemontero** [comment]
@GolanTrevize10 - if you like you can build a local copy of this plugin using the latest at https://github.com/openshift/jenkins-client-plugin to get the updated `openshift.newProject` behavior.

We most likely won't update the openshift jenkins centos images on docker hub until next week.  I'll post an update here when we do.

thanks

**Comment by GolanTrevize10** [comment]
Thanks, I tried the latest version and it works.

**Comment by gabemontero** [comment]
Terrific - thanks for the update.

**Comment by gabemontero** [comment]
final update: v0.9.6 has been cut and the images on docker hub should be updated to include them within the hour
