### ISSUE TITLE
Issue switching to another cluster

### ISSUE THREAD

**Issue by GolanTrevize10** [openshift/jenkins-client-plugin#54]
Hi, I changed the hostname in my cluster configuration in Jenkins and now when I run my pipeline I get this error:

ERROR: new-project returned an error;
{reference={}, err=error: unable to read certificate-authority /var/run/secrets/kubernetes.io/serviceaccount/ca.crt for oldhost.com:8443 due to open /var/run/secrets/kubernetes.io/serviceaccount/ca.crt: no such file or directory, verb=new-project, cmd=oc new-project petclinic-build --skip-config-write --server=https://newhost.com --token=XXXXX , out=, status=1}

I am using an external Jenkins instance outside Openshift

**Comment by gabemontero** [comment]
Did you adjust the server cert authority as needed in the cluster config you changed?

Can you provide a snapshot of the cluster configuration from the Jenkins UI, as well as the pipeline script snippet where you reference that cluster via `openshift.withCluster`?

That error indicates it fell back to attempting to find a cert from the default location.  Either your `withCluster` reference was such that we could not find the cluster, or we did not have a valid cert in the cluster configuration that was found.

**Comment by GolanTrevize10** [comment]
Hi, I didn't add any specific cert authority neither for the old cluster nor the new one. But why is trying to find certificate for the old cluster? IF I switch back to old cluster then it works.

This is my withCluster snippet

withEnv(["PATH+OC=${ocDir}/openshift-origin-client-tools-v3.6.0-c4dd4cf-linux-64bit","SKIP_TLS=true","https_proxy=http://b2b-http.dhl.com:8080"]) {
        // Name of cluster configuration and user token. It is recommended to use a service account instead of your personal user.
        openshift.withCluster( 'example', "${token}" ) {

![image](https://user-images.githubusercontent.com/25170481/30185021-2b904f7a-9420-11e7-88ef-94873b85fb9b.png)

**Comment by gabemontero** [comment]
Well, in your original description, I don't see the `--insecure-skip-tls-verify` option I would expect to see if you are skipping TLS, which you would need to do if you are not adding any certs as you say.  If that is not there, and you don't have a cert in your cluster config, that would explain why as a last resort it attempts to look at the default location.  That is why the oc invocation fails.

As an aside, I see you have set SKIP_TLS in you envs ... in case you were wondering, that is not an env honored by this plugin.

But the disable tls verify on the cluster config you pasted is checked, which should add `--insecure-skip-tls-verify`; either that setting isn't getting propagated, or it is inadvertently getting unchecked when you are switching things around.

I'll need to make some time (should be Friday or Monday) to first try something similar and make sure nothing unexpected is happening.  Otherwise, I might need to give you a debug plugin to try to explicitly print out the various settings as your are switching things around to see why your skip tls setting is getting lost.

**Comment by GolanTrevize10** [comment]
Thanks, now it is working with the skip tls. I didn't try with that checked. Still it is working in old Jenkins instance but in the new one I get the status -2

**Comment by gabemontero** [comment]
ok good thanks for the confirm ... we'll track the -2 with the other issue you've got on that
