### ISSUE TITLE
Using username/password credentials?

### ISSUE THREAD

**Issue by spicysomtam** [openshift/jenkins-client-plugin#60]
I could not get this to work. The only way I could get authenication to work was to use a token, as per the docs. I am not an expert on authentication in openshift, but to get a token I need to login to get it? Also it expires every 24 hours so its not something static? Anyone got an example of using a username/password? Even better would be to update the docs with an example, or tell us why username/password should not be used. I would add that I added the username/password credentials as type  'Openshift Username Password'.

**Comment by jcpowermac** [comment]
@spicysomtam take a look at this doc.
http://playbooks-rhtconsulting.rhcloud.com/playbooks/continuous_delivery/external-jenkins-integration.html
specifically the "Credentials" section.
I haven't looked in the official documentation it might listed there as well.  But the gist is to create a service account and use that token since it doesn't expire.

**Comment by bparees** [comment]
thanks @jcpowermac 

Closing this as that recommendation is spot on... you should be using service accounts for automated processes that need credentials.

**Comment by spicysomtam** [comment]
Thanks for the help. Its much clearer now.
