### ISSUE TITLE
Conditional "when" directive is ignored

### ISSUE THREAD

**Issue by siamaksade** [openshift/jenkins-client-plugin#75]
When using the "when" directive within a declarative pipeline, it gets ignored if the openshift client plugin is used. 

In the following pipeline, both *Build* and *Dev* stages run. If the `openshift.withCluster()` block is removed, then only *Dev* runs.

```
openshift.withCluster() {
    pipeline {
        agent {
            label 'maven'
        }
        stages {
            stage('Build') {
                when {
                    expression {
                        return false
                    }
                }
                steps {
                    echo "Build"
                }
            }
            stage('Dev') {
                when {
                    expression {
                        return true
                    }
                }
                steps {
                    echo "Dev"
                }
            }
        }
    }
}
```

Tested with 1.0.2 and Jenkins Jenkins 2.73.3 on OpenShift v3.7.0-rc.0+d076bb5-181.

**Comment by gabemontero** [comment]
@bparees @coreydaley  @csrwng @jupierce this one is very interesting

it would imply that the `when / expression ` clauses (essentially the mechanism for declarative pipeline to consume jenkins build parameters) are bypassed when this plugin's dsl steps run calls closures, and somehow bypasses whatever magic https://github.com/jenkinsci/pipeline-model-definition-plugin is employing.

I've cloned that repo and have started trying to figure out how those clauses work.

Of course chime in as you see fit in the interim before I report back.

**Comment by csrwng** [comment]
@siamaksade @gabemontero I would say that embedding the new Jenkins pipeline syntax inside an openshisft.withCluster() block is at best untested. I don't think Jenkins supports embedding their pipelines inside other blocks of things. In the release repo we have several pipelines that use the when clause but only use openshift.withCluster() inside a steps block and they all work ok.

@gabemontero it may be worth documenting at least.

**Comment by gabemontero** [comment]
yep I'm leaning that was as well @csrwng but would want to do a bit of due diligence beforehand ... maybe there will be a precise list of thing we can construct for the doc after some small amount of investigation, or a precise of to-do's to document in a card if we can make it work

**Comment by gabemontero** [comment]
OK, I at least have a better understanding of why this is occurring.  

There is a separate parser for declarative through the new pipeline-mode-definition plugin, where it implements the original/scripted pipeline plug point `GlobalVariable` via `org.jenkinsci.plugins.pipeline.modeldefinition.ModelStepLoader`.  When a pipeline script starts with `pipeline {`, the new parser is called, where it references original/scripted parsing via `CpsScript` when needed.

Once we venture into our fluent syntax, we loose the additional, dynamic parsing of declarative (which has a `org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter` which is similar in a lot of ways to our OpenShiftDSL.groovy.

I spent a couple of hours trying to hack our groovy to call ModelInterpreter, but no luck.  The lower level groovy libraries prevented it.  Most likely they have fail safes so hijack jobs like I tried are not possible, but I did not further dive in groovy to confirm.

Net result:
1) we doc that the best practice for our dsl and declarative is the flip the nesting @siamaksade used ... i.e. `pipeline {` is the top level, and then `openshift.withCluster {`, etc. are within the various blocks, otherwise you lose some declarative functionality

2) a research trello card could be worthwhile to continue the investigation / experiment I described above; either a viable work around emerges ... less likely, but maybe the research gives us enough ammo to convince cloudbees the patter is worthwhile and update their structure to allow plugging into declarative in a first class manner

thoughts of course welcome

**Comment by bparees** [comment]
is it even valid to use the pipeline declaration inside something else?  are there any other examples of this working?

**Comment by siamaksade** [comment]
@bparees  The examples works except the `when` blocks. However, you might be right that it shouldn't be used that way with `pipeline`. In all scripted examples of the plugin, `openshift.withCluster()` is the root element and I followed the same pattern.

I tested what @csrwng suggested and that works:
```
pipeline {
  stages {
    stage('Build') {
      when {
        expression {
          openshift.withCluster() {
            return !openshift.selector('bc', 'mapit-spring').exists();
          }
        }
      }
      steps {
        script {
          openshift.withCluster() {
            openshift.newApp('redhat-openjdk18-openshift:1.1~https://github.com/siamaksade/mapit-spring.git')
          }
        }
      }
    }
  }
}
```

**Comment by bparees** [comment]
>  In all scripted examples of the plugin, openshift.withCluster() is the root element and I followed the same pattern.

right but declarative has its own pattern which is "start with the pipeline element" which i think supercedes anything about the client plugin.

```
All valid Declarative Pipelines must be enclosed within a pipeline block, for example:
```

https://jenkins.io/doc/book/pipeline/syntax/#declarative-pipeline

**Comment by gabemontero** [comment]
@siamaksade - glad the suggestion worked for you

@bparees @siamaksade @csrwng @coreydaley wrt documenting "when to use which pattern", given the (lack of) maturity wrt combining declarative with openshift fluent dsl, I propose first documenting all this in this plugin's readme (where presumably we'll add more tidbits as they are discovered), and then when things sufficiently progress, migrate as appropriate to official openshift docs.  Thoughts?  Is so, I'll use this issue to drive the doc update.

For the research item I mentioned earlier, I've opened https://trello.com/c/WI10qGHh/1414-pipelineintegration-research-ways-to-have-openshift-jenkins-client-fluent-dls-in-pipeline-include-declarative-pipeline-dsl

**Comment by bparees** [comment]
>  I propose first documenting all this in this plugin's readme

documenting what?

Until I see otherwise, i'm still of the opinion that any jenkinsfile that does not start with "pipeline{" should not be using declarative syntax, and that's nothing specific to the openshift client plugin and not deserving of special documentation, that's "how you use the declarative syntax in a jenkinsfile"

**Comment by gabemontero** [comment]
My assumption was a lot of our users won't be that savvy / cognizant, and a simple blurb highlighting this distinction could offset issues getting opened and questions getting asked.

But I don't feel overly strong about it.  If I'm in the minority here, I'm cool with just closing this out then.

**Comment by bparees** [comment]
my vote is if we get a second issue on it we can add the blurb/example of using it in a declarative pipeline.  my fear is the syntax changes yet again and we're left w/ yet more outdated warnings/doc.

**Comment by jupierce** [comment]
I'm guessing the safest advice we can provide is that openshift DSL closures should only contain:
1. other openshift DSL
2. standard groovy statements (e.g. if/then/for/etc)
3. simple Jenkins pipeline steps (nothing with its own closure; e.g. readFile is ok, but parallel or stage is not advisable)

Other patterns work now, but Jenkins is clearly a moving target.

**Comment by gabemontero** [comment]
+1 @bparees and @jupierce 

closing out
