### ISSUE TITLE
Enable CA Verify with insecure-skip-tls-verify: true is broken

### ISSUE THREAD

**Issue by elconas** [openshift/jenkins-client-plugin#89]
When having this configured in ~jenkins/.kube/config on the os level
 
```
- cluster:
    insecure-skip-tls-verify: true
```
 
I can not enable SSL verify on the cluster Level in Jenkins. I will always get:
 
```
  action failed: {reference={}, err=error: specifying a root certificates file with the insecure flag is not allowed, verb=get
```
 
This should be possible. The plugin should not depend on System configuration

  * Setting KUBECONFIG to something sane, or 
  * overwriting insecure-skip-tls-verify always (even if false)) or (best)
  * allow setting ENV VARS at the global cluster level.
 
Workaround: Wrap in withEnv(["KUBECONFIG=${workspace}"]) - with deleteDir() in a finally block

**Comment by gabemontero** [comment]
hey @elconas  - "depend" is not really the right word in "The plugin should not depend on System configuration" ... I would say ""... should not get tripped up ... "  ;-)

this issue is the plugin to date has been assuming there is no `.kube/config` file present, hence when
the oc binary is forked and finds the `.kube/config` path off of `$HOME`, it reads in those settings and they conflict with what the args to `oc` that the plugin constructs prior to forking the `oc` command.

so both short and long term possibilities exist wrt to precedence of config specified, and whether the plugin should even support the use of `.kube\config`, and if so, orders of precedence choices and option merging.

I'm currently of the following opinion
1) short term, do not support use of `.kube/config1, and essentially mimic @elconas 's workaround - set `KUBECONFIG` to a location that does not have the conflicting `.kube/config` file

In some experimentation bring up our jenkins image via the template in a pod, I am seeing that KUBECONFIG=/var/lib/origin/openshift.local.config/master/admin.kubeconfig is set.  However, that file does not in fact exist in the pod.  I'm leaning toward that (vs. WORKSPACE, where a person running jenkins outside of an openshift pod might leverage that location, even accidentally, for `oc login`.

And drive this change via this issue and the PR I'll compose for it.

2) long term, open a trello feature card for exploring the requirement for devising a config merging order of precedence similar to the `oc` binary, but include any arg overrides introduced via use of this plugin's DSL as part of that precedence. 

@bparees @coreydaley @elconas - opinions of course welcome

thanks

**Comment by bparees** [comment]
> KUBECONFIG=/var/lib/origin/openshift.local.config/master/admin.kubeconfig

i'd like to know what is setting that. i'm pretty sure it's not our jenkins template...  so is that set in all pods on the cluster?

**Comment by gabemontero** [comment]
On Wed, Nov 29, 2017 at 11:47 PM, Ben Parees <notifications@github.com>
wrote:

> KUBECONFIG=/var/lib/origin/openshift.local.config/master/admin.kubeconfig
>
> i'd like to know what is setting that. i'm pretty sure it's not our
> jenkins template... so is that set in all pods on the cluster?
>
The origin image sets it:
https://github.com/openshift/origin/blob/master/images/origin/Dockerfile#L27

When the jenkins image started to build based off of the origin image, we
started to pick that up as a default.

**Comment by gabemontero** [comment]
Going to close this out with a doc update since our 3.7 image is now setting KUBECONFIG and there is not a need to  ... see discussion in https://github.com/openshift/jenkins-client-plugin/pull/90#issuecomment-348304477 and earlier comments in that pull

Either run from the image in a pod to get the default KUBECONFIG set.

If you are running outside openshift and have kube config files in your home dir such that `oc` will find it, it is your responsibility at that point to manage its settings in conjunction to what you are doing from the pipeline.

That will be the crux of the doc update, which will close this out once the content is agreed upon and we merge.
