### ISSUE TITLE
Stop spamming the pipeline with sub-step information

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/jenkins-client-plugin#97]
@jupierce used the quiet listener factory or whatever to stop a bunch of output from being shown inside of the watch -- would be great to get _every_ output of `openshift` to not spam my pipeline with 

```
[Pipeline] readFile
[Pipeline] readFile
[Pipeline] _OcAction
[Pipeline] readFile
[Pipeline] readFile
[Pipeline] _OcAction

[Pipeline] readFile
[Pipeline] readFile
[Pipeline] _OcAction
```

/cc @bparees @gabemontero

**Comment by gabemontero** [comment]
The quiet listener is employed both in OcWatch and OcAction during the Execution.run extension point.  These are our only entryways into the durable task plugin code.  It *appears* more effective in the watch case since we controls the enclosure, and hence the task listener used for logging..  But when you are talking your entire pipeline, the workflow/pipeline plugin itself has first crack at that.  We cannot control that Task Listener / logger it uses.

I did some internet searching on how you might control the pipeline engine's logging, but nothing came up.

Apologies - no solution for you possible within this plugin here.

**Comment by stevekuznetsov** [comment]
😢
